"use client";

import { useEffect, useRef } from "react";
import { EditorView, keymap, lineNumbers, highlightActiveLine, highlightActiveLineGutter } from "@codemirror/view";
import { EditorState } from "@codemirror/state";
import { defaultKeymap, history, historyKeymap } from "@codemirror/commands";
import { bracketMatching, foldGutter, HighlightStyle, syntaxHighlighting } from "@codemirror/language";
import { autocompletion, closeBrackets, startCompletion, type CompletionContext, type CompletionResult } from "@codemirror/autocomplete";
import { tags } from "@lezer/highlight";
import { javascript } from "@codemirror/lang-javascript";
import { python } from "@codemirror/lang-python";
import { cpp } from "@codemirror/lang-cpp";
import { java } from "@codemirror/lang-java";
import { rust } from "@codemirror/lang-rust";
import { html } from "@codemirror/lang-html";
import { css } from "@codemirror/lang-css";
import { useTheme } from "@/components/landing/ThemeContext";

const languageExtensions: Record<string, any> = {
  javascript: javascript(),
  typescript: javascript({ typescript: true }),
  python: python(),
  cpp: cpp(),
  java: java(),
  rust: rust(),
  go: javascript(),
  ruby: javascript(),
  haskell: javascript(),
  c: cpp(),
  html: html(),
  css: css(),
};

// Language-specific completions
const languageCompletions: Record<string, { label: string; type: string; detail?: string }[]> = {
  javascript: [
    { label: "console.log", type: "method", detail: "Log to console" },
    { label: "console.error", type: "method", detail: "Log error" },
    { label: "console.warn", type: "method", detail: "Log warning" },
    { label: "setTimeout", type: "function", detail: "Execute after delay" },
    { label: "setInterval", type: "function", detail: "Repeat execution" },
    { label: "fetch", type: "function", detail: "HTTP request" },
    { label: "JSON.parse", type: "method", detail: "Parse JSON string" },
    { label: "JSON.stringify", type: "method", detail: "Stringify object" },
    { label: "Math.floor", type: "method", detail: "Round down" },
    { label: "Math.ceil", type: "method", detail: "Round up" },
    { label: "Math.random", type: "method", detail: "Random number" },
    { label: "Array.isArray", type: "method", detail: "Check if array" },
    { label: "Object.keys", type: "method", detail: "Get object keys" },
    { label: "Object.values", type: "method", detail: "Get object values" },
    { label: "Promise", type: "class", detail: "Async promise" },
    { label: "async", type: "keyword", detail: "Async function" },
    { label: "await", type: "keyword", detail: "Wait for promise" },
    { label: "function", type: "keyword" },
    { label: "const", type: "keyword" },
    { label: "let", type: "keyword" },
    { label: "var", type: "keyword" },
    { label: "return", type: "keyword" },
    { label: "if", type: "keyword" },
    { label: "else", type: "keyword" },
    { label: "for", type: "keyword" },
    { label: "while", type: "keyword" },
    { label: "switch", type: "keyword" },
    { label: "case", type: "keyword" },
    { label: "break", type: "keyword" },
    { label: "continue", type: "keyword" },
    { label: "try", type: "keyword" },
    { label: "catch", type: "keyword" },
    { label: "throw", type: "keyword" },
    { label: "new", type: "keyword" },
    { label: "class", type: "keyword" },
    { label: "extends", type: "keyword" },
    { label: "import", type: "keyword" },
    { label: "export", type: "keyword" },
    { label: "default", type: "keyword" },
    { label: "from", type: "keyword" },
    { label: "map", type: "method", detail: "Transform array" },
    { label: "filter", type: "method", detail: "Filter array" },
    { label: "reduce", type: "method", detail: "Reduce array" },
    { label: "forEach", type: "method", detail: "Iterate array" },
    { label: "find", type: "method", detail: "Find element" },
    { label: "includes", type: "method", detail: "Check inclusion" },
    { label: "indexOf", type: "method", detail: "Find index" },
    { label: "push", type: "method", detail: "Add to end" },
    { label: "pop", type: "method", detail: "Remove from end" },
    { label: "splice", type: "method", detail: "Add/remove elements" },
    { label: "split", type: "method", detail: "Split string" },
    { label: "join", type: "method", detail: "Join array" },
    { label: "replace", type: "method", detail: "Replace in string" },
    { label: "trim", type: "method", detail: "Trim whitespace" },
    { label: "length", type: "property", detail: "Get length" },
    { label: "true", type: "keyword" },
    { label: "false", type: "keyword" },
    { label: "null", type: "keyword" },
    { label: "undefined", type: "keyword" },
    { label: "typeof", type: "keyword" },
    { label: "instanceof", type: "keyword" },
  ],
  typescript: [
    { label: "console.log", type: "method", detail: "Log to console" },
    { label: "console.error", type: "method", detail: "Log error" },
    { label: "console.warn", type: "method", detail: "Log warning" },
    { label: "setTimeout", type: "function", detail: "Execute after delay" },
    { label: "setInterval", type: "function", detail: "Repeat execution" },
    { label: "fetch", type: "function", detail: "HTTP request" },
    { label: "JSON.parse", type: "method", detail: "Parse JSON string" },
    { label: "JSON.stringify", type: "method", detail: "Stringify object" },
    { label: "Promise", type: "class", detail: "Async promise" },
    { label: "async", type: "keyword", detail: "Async function" },
    { label: "await", type: "keyword", detail: "Wait for promise" },
    { label: "interface", type: "keyword", detail: "Define interface" },
    { label: "type", type: "keyword", detail: "Define type alias" },
    { label: "enum", type: "keyword", detail: "Define enumeration" },
    { label: "readonly", type: "keyword", detail: "Read-only modifier" },
    { label: "keyof", type: "keyword", detail: "Keyof type operator" },
    { label: "implements", type: "keyword", detail: "Implement interface" },
    { label: "abstract", type: "keyword", detail: "Abstract class" },
    { label: "as", type: "keyword", detail: "Type assertion" },
    { label: "namespace", type: "keyword", detail: "Define namespace" },
    { label: "Record", type: "type", detail: "Record utility type" },
    { label: "Partial", type: "type", detail: "Partial utility type" },
    { label: "Required", type: "type", detail: "Required utility type" },
    { label: "Pick", type: "type", detail: "Pick utility type" },
    { label: "Omit", type: "type", detail: "Omit utility type" },
    { label: "Array", type: "type", detail: "Array type" },
    { label: "Map", type: "type", detail: "Map type" },
    { label: "Set", type: "type", detail: "Set type" },
    { label: "function", type: "keyword" },
    { label: "const", type: "keyword" },
    { label: "let", type: "keyword" },
    { label: "return", type: "keyword" },
    { label: "if", type: "keyword" },
    { label: "else", type: "keyword" },
    { label: "for", type: "keyword" },
    { label: "while", type: "keyword" },
    { label: "switch", type: "keyword" },
    { label: "case", type: "keyword" },
    { label: "break", type: "keyword" },
    { label: "continue", type: "keyword" },
    { label: "try", type: "keyword" },
    { label: "catch", type: "keyword" },
    { label: "throw", type: "keyword" },
    { label: "new", type: "keyword" },
    { label: "class", type: "keyword" },
    { label: "extends", type: "keyword" },
    { label: "import", type: "keyword" },
    { label: "export", type: "keyword" },
    { label: "default", type: "keyword" },
    { label: "from", type: "keyword" },
    { label: "string", type: "type" },
    { label: "number", type: "type" },
    { label: "boolean", type: "type" },
    { label: "any", type: "type" },
    { label: "void", type: "type" },
    { label: "never", type: "type" },
    { label: "unknown", type: "type" },
    { label: "null", type: "keyword" },
    { label: "undefined", type: "keyword" },
    { label: "true", type: "keyword" },
    { label: "false", type: "keyword" },
  ],
  python: [
    { label: "print", type: "function", detail: "Output to console" },
    { label: "len", type: "function", detail: "Length of sequence" },
    { label: "range", type: "function", detail: "Generate range" },
    { label: "int", type: "function", detail: "Convert to integer" },
    { label: "float", type: "function", detail: "Convert to float" },
    { label: "str", type: "function", detail: "Convert to string" },
    { label: "list", type: "function", detail: "Create list" },
    { label: "dict", type: "function", detail: "Create dictionary" },
    { label: "set", type: "function", detail: "Create set" },
    { label: "tuple", type: "function", detail: "Create tuple" },
    { label: "input", type: "function", detail: "User input" },
    { label: "open", type: "function", detail: "Open file" },
    { label: "type", type: "function", detail: "Get type" },
    { label: "isinstance", type: "function", detail: "Check type" },
    { label: "enumerate", type: "function", detail: "Enumerate iterable" },
    { label: "zip", type: "function", detail: "Zip iterables" },
    { label: "map", type: "function", detail: "Map function" },
    { label: "filter", type: "function", detail: "Filter iterable" },
    { label: "sorted", type: "function", detail: "Sort iterable" },
    { label: "reversed", type: "function", detail: "Reverse iterable" },
    { label: "abs", type: "function", detail: "Absolute value" },
    { label: "max", type: "function", detail: "Maximum value" },
    { label: "min", type: "function", detail: "Minimum value" },
    { label: "sum", type: "function", detail: "Sum values" },
    { label: "round", type: "function", detail: "Round number" },
    { label: "True", type: "keyword" },
    { label: "False", type: "keyword" },
    { label: "None", type: "keyword" },
    { label: "def", type: "keyword" },
    { label: "class", type: "keyword" },
    { label: "if", type: "keyword" },
    { label: "elif", type: "keyword" },
    { label: "else", type: "keyword" },
    { label: "for", type: "keyword" },
    { label: "while", type: "keyword" },
    { label: "return", type: "keyword" },
    { label: "import", type: "keyword" },
    { label: "from", type: "keyword" },
    { label: "as", type: "keyword" },
    { label: "try", type: "keyword" },
    { label: "except", type: "keyword" },
    { label: "finally", type: "keyword" },
    { label: "raise", type: "keyword" },
    { label: "with", type: "keyword" },
    { label: "lambda", type: "keyword" },
    { label: "yield", type: "keyword" },
    { label: "pass", type: "keyword" },
    { label: "break", type: "keyword" },
    { label: "continue", type: "keyword" },
    { label: "in", type: "keyword" },
    { label: "not", type: "keyword" },
    { label: "and", type: "keyword" },
    { label: "or", type: "keyword" },
  ],
  cpp: [
    { label: "#include", type: "keyword", detail: "Include header" },
    { label: "std::cout", type: "method", detail: "Standard output" },
    { label: "std::cin", type: "method", detail: "Standard input" },
    { label: "std::endl", type: "method", detail: "End line flush" },
    { label: "std::string", type: "class", detail: "String class" },
    { label: "std::vector", type: "class", detail: "Dynamic array" },
    { label: "std::map", type: "class", detail: "Ordered map" },
    { label: "std::set", type: "class", detail: "Ordered set" },
    { label: "std::sort", type: "function", detail: "Sort range" },
    { label: "std::find", type: "function", detail: "Find in range" },
    { label: "std::min", type: "function", detail: "Minimum value" },
    { label: "std::max", type: "function", detail: "Maximum value" },
    { label: "std::to_string", type: "function", detail: "Convert to string" },
    { label: "std::stoi", type: "function", detail: "String to int" },
    { label: "std::getline", type: "function", detail: "Read line" },
    { label: "push_back", type: "method", detail: "Add to vector" },
    { label: "begin", type: "method", detail: "Iterator to start" },
    { label: "end", type: "method", detail: "Iterator to end" },
    { label: "size", type: "method", detail: "Container size" },
    { label: "class", type: "keyword" },
    { label: "template", type: "keyword" },
    { label: "namespace", type: "keyword" },
    { label: "public", type: "keyword" },
    { label: "private", type: "keyword" },
    { label: "protected", type: "keyword" },
    { label: "virtual", type: "keyword" },
    { label: "override", type: "keyword" },
    { label: "auto", type: "keyword" },
    { label: "nullptr", type: "keyword", detail: "Null pointer" },
    { label: "const", type: "keyword" },
    { label: "static", type: "keyword" },
    { label: "struct", type: "keyword" },
    { label: "enum", type: "keyword" },
    { label: "typedef", type: "keyword" },
    { label: "using", type: "keyword" },
    { label: "return", type: "keyword" },
    { label: "if", type: "keyword" },
    { label: "else", type: "keyword" },
    { label: "for", type: "keyword" },
    { label: "while", type: "keyword" },
    { label: "do", type: "keyword" },
    { label: "switch", type: "keyword" },
    { label: "case", type: "keyword" },
    { label: "break", type: "keyword" },
    { label: "continue", type: "keyword" },
    { label: "try", type: "keyword" },
    { label: "catch", type: "keyword" },
    { label: "throw", type: "keyword" },
    { label: "new", type: "keyword" },
    { label: "delete", type: "keyword" },
    { label: "true", type: "keyword" },
    { label: "false", type: "keyword" }
  ],
  java: [
    { label: "System.out.println", type: "method", detail: "Print line" },
    { label: "System.out.print", type: "method", detail: "Print" },
    { label: "System.out.printf", type: "method", detail: "Formatted print" },
    { label: "Scanner", type: "class", detail: "Input scanner" },
    { label: "ArrayList", type: "class", detail: "Dynamic array" },
    { label: "HashMap", type: "class", detail: "Hash map" },
    { label: "LinkedList", type: "class", detail: "Linked list" },
    { label: "HashSet", type: "class", detail: "Hash set" },
    { label: "Collections.sort", type: "method", detail: "Sort list" },
    { label: "String.valueOf", type: "method", detail: "Convert to string" },
    { label: "Integer.parseInt", type: "method", detail: "Parse integer" },
    { label: "Math.max", type: "method", detail: "Maximum value" },
    { label: "Math.min", type: "method", detail: "Minimum value" },
    { label: "Math.abs", type: "method", detail: "Absolute value" },
    { label: "import", type: "keyword" },
    { label: "public", type: "keyword" },
    { label: "private", type: "keyword" },
    { label: "protected", type: "keyword" },
    { label: "static", type: "keyword" },
    { label: "final", type: "keyword" },
    { label: "class", type: "keyword" },
    { label: "interface", type: "keyword" },
    { label: "extends", type: "keyword" },
    { label: "implements", type: "keyword" },
    { label: "return", type: "keyword" },
    { label: "new", type: "keyword" },
    { label: "this", type: "keyword" },
    { label: "super", type: "keyword" },
    { label: "try", type: "keyword" },
    { label: "catch", type: "keyword" },
    { label: "finally", type: "keyword" },
    { label: "throw", type: "keyword" },
    { label: "throws", type: "keyword" },
    { label: "void", type: "type" },
    { label: "int", type: "type" },
    { label: "String", type: "type" },
    { label: "boolean", type: "type" },
    { label: "double", type: "type" },
    { label: "float", type: "type" },
    { label: "long", type: "type" },
    { label: "char", type: "type" },
    { label: "if", type: "keyword" },
    { label: "else", type: "keyword" },
    { label: "for", type: "keyword" },
    { label: "while", type: "keyword" },
    { label: "do", type: "keyword" },
    { label: "switch", type: "keyword" },
    { label: "case", type: "keyword" },
    { label: "break", type: "keyword" },
    { label: "continue", type: "keyword" },
    { label: "true", type: "keyword" },
    { label: "false", type: "keyword" },
    { label: "null", type: "keyword" }
  ],
  go: [
    { label: "fmt.Println", type: "function", detail: "Print line" },
    { label: "fmt.Printf", type: "function", detail: "Formatted print" },
    { label: "fmt.Sprintf", type: "function", detail: "Format string" },
    { label: "fmt.Sprintf", type: "function", detail: "Format to string" },
    { label: "fmt.Scanln", type: "function", detail: "Read input" },
    { label: "len", type: "function", detail: "Length" },
    { label: "cap", type: "function", detail: "Capacity" },
    { label: "make", type: "function", detail: "Make slice/map/channel" },
    { label: "new", type: "function", detail: "Allocate memory" },
    { label: "append", type: "function", detail: "Append to slice" },
    { label: "copy", type: "function", detail: "Copy slice" },
    { label: "panic", type: "function", detail: "Panic" },
    { label: "recover", type: "function", detail: "Recover from panic" },
    { label: "func", type: "keyword", detail: "Function" },
    { label: "var", type: "keyword" },
    { label: "const", type: "keyword" },
    { label: "if", type: "keyword" },
    { label: "else", type: "keyword" },
    { label: "for", type: "keyword" },
    { label: "range", type: "keyword" },
    { label: "switch", type: "keyword" },
    { label: "case", type: "keyword" },
    { label: "default", type: "keyword" },
    { label: "return", type: "keyword" },
    { label: "defer", type: "keyword", detail: "Defer execution" },
    { label: "go", type: "keyword", detail: "Goroutine" },
    { label: "chan", type: "keyword", detail: "Channel" },
    { label: "map", type: "keyword" },
    { label: "struct", type: "keyword" },
    { label: "interface", type: "keyword" },
    { label: "package", type: "keyword" },
    { label: "import", type: "keyword" },
    { label: "type", type: "keyword" },
    { label: "select", type: "keyword" },
    { label: "case", type: "keyword" },
    { label: "break", type: "keyword" },
    { label: "continue", type: "keyword" },
    { label: "true", type: "keyword" },
    { label: "false", type: "keyword" },
    { label: "nil", type: "keyword" },
    { label: "error", type: "type", detail: "Error interface" },
    { label: "string", type: "type" },
    { label: "int", type: "type" },
    { label: "bool", type: "type" },
    { label: "float64", type: "type" }
  ],
  ruby: [
    { label: "puts", type: "function", detail: "Print line" },
    { label: "print", type: "function", detail: "Print" },
    { label: "gets", type: "function", detail: "Read line" },
    { label: "require", type: "function", detail: "Require library" },
    { label: "include", type: "keyword", detail: "Include module" },
    { label: "attr_reader", type: "keyword", detail: "Reader methods" },
    { label: "attr_writer", type: "keyword", detail: "Writer methods" },
    { label: "attr_accessor", type: "keyword", detail: "Accessors" },
    { label: "lambda", type: "keyword", detail: "Lambda" },
    { label: "proc", type: "keyword", detail: "Proc object" },
    { label: "yield", type: "keyword", detail: "Yield to block" },
    { label: "def", type: "keyword", detail: "Define method" },
    { label: "end", type: "keyword" },
    { label: "class", type: "keyword" },
    { label: "module", type: "keyword" },
    { label: "if", type: "keyword" },
    { label: "else", type: "keyword" },
    { label: "elsif", type: "keyword" },
    { label: "unless", type: "keyword" },
    { label: "while", type: "keyword" },
    { label: "until", type: "keyword" },
    { label: "for", type: "keyword" },
    { label: "do", type: "keyword" },
    { label: "return", type: "keyword" },
    { label: "raise", type: "keyword", detail: "Raise exception" },
    { label: "begin", type: "keyword" },
    { label: "rescue", type: "keyword" },
    { label: "ensure", type: "keyword" },
    { label: "self", type: "keyword" },
    { label: "nil", type: "keyword" },
    { label: "true", type: "keyword" },
    { label: "false", type: "keyword" },
    { label: "puts", type: "function" },
    { label: "each", type: "method", detail: "Iterate" },
    { label: "map", type: "method", detail: "Transform" },
    { label: "select", type: "method", detail: "Filter" },
    { label: "reject", type: "method", detail: "Filter out" },
    { label: "reduce", type: "method", detail: "Accumulate" },
    { label: "length", type: "method", detail: "Size" },
    { label: "push", type: "method", detail: "Add element" },
    { label: "pop", type: "method", detail: "Remove last" },
    { label: "first", type: "method", detail: "First element" },
    { label: "last", type: "method", detail: "Last element" },
    { label: "empty?", type: "method", detail: "Check empty" },
    { label: "include?", type: "method", detail: "Check inclusion" },
    { label: "to_s", type: "method", detail: "To string" },
    { label: "to_i", type: "method", detail: "To integer" },
    { label: "to_f", type: "method", detail: "To float" }
  ],
  rust: [
    { label: "println!", type: "function", detail: "Print with newline" },
    { label: "print!", type: "function", detail: "Print without newline" },
    { label: "format!", type: "function", detail: "Format to string" },
    { label: "vec!", type: "function", detail: "Create vector" },
    { label: "String::new", type: "method", detail: "New empty string" },
    { label: "String::from", type: "method", detail: "String from literal" },
    { label: "Vec::new", type: "method", detail: "New empty vector" },
    { label: "push", type: "method", detail: "Add to vector" },
    { label: "pop", type: "method", detail: "Remove last" },
    { label: "len", type: "method", detail: "Length" },
    { label: "is_empty", type: "method", detail: "Check empty" },
    { label: "unwrap", type: "method", detail: "Unwrap Option/Result" },
    { label: "expect", type: "method", detail: "Unwrap or panic" },
    { label: "as_ref", type: "method", detail: "Borrow as reference" },
    { label: "clone", type: "method", detail: "Clone value" },
    { label: "to_string", type: "method", detail: "Convert to string" },
    { label: "parse", type: "method", detail: "Parse string" },
    { label: "iter", type: "method", detail: "Get iterator" },
    { label: "collect", type: "method", detail: "Collect iterator" },
    { label: "map", type: "method", detail: "Transform iterator" },
    { label: "filter", type: "method", detail: "Filter iterator" },
    { label: "fn", type: "keyword", detail: "Function" },
    { label: "let", type: "keyword" },
    { label: "let mut", type: "keyword", detail: "Mutable binding" },
    { label: "pub", type: "keyword", detail: "Public visibility" },
    { label: "struct", type: "keyword" },
    { label: "enum", type: "keyword" },
    { label: "impl", type: "keyword", detail: "Implementation" },
    { label: "trait", type: "keyword", detail: "Define trait" },
    { label: "match", type: "keyword", detail: "Pattern match" },
    { label: "if", type: "keyword" },
    { label: "else", type: "keyword" },
    { label: "for", type: "keyword" },
    { label: "while", type: "keyword" },
    { label: "loop", type: "keyword", detail: "Infinite loop" },
    { label: "return", type: "keyword" },
    { label: "self", type: "keyword" },
    { label: "Self", type: "keyword", detail: "Self type" },
    { label: "use", type: "keyword", detail: "Import" },
    { label: "mod", type: "keyword", detail: "Module" },
    { label: "where", type: "keyword" },
    { label: "type", type: "keyword" },
    { label: "async", type: "keyword" },
    { label: "await", type: "keyword" },
    { label: "move", type: "keyword" },
    { label: "mut", type: "keyword", detail: "Mutable" },
    { label: "ref", type: "keyword", detail: "Reference" },
    { label: "dyn", type: "keyword", detail: "Dynamic dispatch" },
    { label: "String", type: "type" },
    { label: "Vec", type: "type" },
    { label: "Option", type: "type" },
    { label: "Result", type: "type" },
    { label: "Ok", type: "constructor" },
    { label: "Err", type: "constructor" },
    { label: "Some", type: "constructor" },
    { label: "None", type: "constructor" },
    { label: "true", type: "keyword" },
    { label: "false", type: "keyword" }
  ],
  haskell: [
    { label: "putStrLn", type: "function", detail: "Print line" },
    { label: "print", type: "function", detail: "Print value" },
    { label: "putStr", type: "function", detail: "Print string" },
    { label: "getLine", type: "function", detail: "Read line" },
    { label: "getContents", type: "function", detail: "Read all input" },
    { label: "map", type: "function", detail: "Map function over list" },
    { label: "filter", type: "function", detail: "Filter list" },
    { label: "foldl", type: "function", detail: "Fold left" },
    { label: "foldr", type: "function", detail: "Fold right" },
    { label: "head", type: "function", detail: "First element" },
    { label: "tail", type: "function", detail: "All but first" },
    { label: "length", type: "function", detail: "List length" },
    { label: "reverse", type: "function", detail: "Reverse list" },
    { label: "zip", type: "function", detail: "Zip two lists" },
    { label: "fst", type: "function", detail: "First of pair" },
    { label: "snd", type: "function", detail: "Second of pair" },
    { label: "head", type: "function", detail: "First element" },
    { label: "abs", type: "function", detail: "Absolute value" },
    { label: "max", type: "function", detail: "Maximum" },
    { label: "min", type: "function", detail: "Minimum" },
    { label: "null", type: "function", detail: "Check empty list" },
    { label: "otherwise", type: "keyword", detail: "Catch all" },
    { label: "where", type: "keyword" },
    { label: "let", type: "keyword" },
    { label: "in", type: "keyword" },
    { label: "if", type: "keyword" },
    { label: "then", type: "keyword" },
    { label: "else", type: "keyword" },
    { label: "case", type: "keyword" },
    { label: "of", type: "keyword" },
    { label: "do", type: "keyword" },
    { label: "module", type: "keyword" },
    { label: "import", type: "keyword" },
    { label: "data", type: "keyword" },
    { label: "type", type: "keyword" },
    { label: "class", type: "keyword" },
    { label: "instance", type: "keyword" },
    { label: "deriving", type: "keyword" },
    { label: "True", type: "keyword" },
    { label: "False", type: "keyword" },
    { label: "not", type: "function", detail: "Boolean not" },
    { label: "&&", type: "keyword", detail: "Boolean and" },
    { label: "||", type: "keyword", detail: "Boolean or" },
    { label: "Maybe", type: "class", detail: "Maybe type" },
    { label: "Just", type: "constructor", detail: "Just value" },
    { label: "Nothing", type: "constructor", detail: "Nothing value" },
    { label: "IO", type: "type", detail: "IO monad" },
    { label: "String", type: "type", detail: "String type" },
    { label: "Int", type: "type", detail: "Integer type" },
    { label: "Char", type: "type", detail: "Character type" },
  ],
  c: [
    { label: "printf", type: "function", detail: "Print formatted output" },
    { label: "scanf", type: "function", detail: "Read formatted input" },
    { label: "fprintf", type: "function", detail: "Print to file" },
    { label: "fscanf", type: "function", detail: "Read from file" },
    { label: "sprintf", type: "function", detail: "Print to string" },
    { label: "malloc", type: "function", detail: "Allocate memory" },
    { label: "calloc", type: "function", detail: "Allocate zeroed memory" },
    { label: "realloc", type: "function", detail: "Reallocate memory" },
    { label: "free", type: "function", detail: "Free memory" },
    { label: "strlen", type: "function", detail: "String length" },
    { label: "strcpy", type: "function", detail: "Copy string" },
    { label: "strcat", type: "function", detail: "Concatenate strings" },
    { label: "strcmp", type: "function", detail: "Compare strings" },
    { label: "memcpy", type: "function", detail: "Copy memory" },
    { label: "memset", type: "function", detail: "Set memory" },
    { label: "fopen", type: "function", detail: "Open file" },
    { label: "fclose", type: "function", detail: "Close file" },
    { label: "fread", type: "function", detail: "Read from file" },
    { label: "fwrite", type: "function", detail: "Write to file" },
    { label: "fgets", type: "function", detail: "Read line from file" },
    { label: "fputs", type: "function", detail: "Write string to file" },
    { label: "abs", type: "function", detail: "Absolute value" },
    { label: "pow", type: "function", detail: "Power" },
    { label: "sqrt", type: "function", detail: "Square root" },
    { label: "ceil", type: "function", detail: "Round up" },
    { label: "floor", type: "function", detail: "Round down" },
    { label: "int", type: "type", detail: "Integer type" },
    { label: "float", type: "type", detail: "Float type" },
    { label: "double", type: "type", detail: "Double type" },
    { label: "char", type: "type", detail: "Character type" },
    { label: "void", type: "type", detail: "Void type" },
    { label: "struct", type: "keyword" },
    { label: "enum", type: "keyword" },
    { label: "typedef", type: "keyword" },
    { label: "return", type: "keyword" },
    { label: "if", type: "keyword" },
    { label: "else", type: "keyword" },
    { label: "for", type: "keyword" },
    { label: "while", type: "keyword" },
    { label: "do", type: "keyword" },
    { label: "switch", type: "keyword" },
    { label: "case", type: "keyword" },
    { label: "break", type: "keyword" },
    { label: "continue", type: "keyword" },
    { label: "#include", type: "keyword", detail: "Include header" },
    { label: "#define", type: "keyword", detail: "Macro definition" },
    { label: "#ifdef", type: "keyword", detail: "If defined" },
    { label: "#ifndef", type: "keyword", detail: "If not defined" },
    { label: "NULL", type: "keyword", detail: "Null pointer" },
    { label: "sizeof", type: "keyword", detail: "Size of type" },
    { label: "static", type: "keyword" },
    { label: "extern", type: "keyword" },
    { label: "const", type: "keyword" },
    { label: "sizeof", type: "keyword" },
    { label: "main", type: "function", detail: "Main entry point" },
  ],
  html: [
    { label: "<!DOCTYPE html>", type: "keyword", detail: "Document type declaration" },
    { label: "<html>", type: "tag", detail: "Root element" },
    { label: "<head>", type: "tag", detail: "Document head" },
    { label: "<body>", type: "tag", detail: "Document body" },
    { label: "<div>", type: "tag", detail: "Division container" },
    { label: "<span>", type: "tag", detail: "Inline container" },
    { label: "<p>", type: "tag", detail: "Paragraph" },
    { label: "<h1>", type: "tag", detail: "Heading level 1" },
    { label: "<h2>", type: "tag", detail: "Heading level 2" },
    { label: "<h3>", type: "tag", detail: "Heading level 3" },
    { label: "<a>", type: "tag", detail: "Anchor/Link" },
    { label: "<img>", type: "tag", detail: "Image" },
    { label: "<ul>", type: "tag", detail: "Unordered list" },
    { label: "<ol>", type: "tag", detail: "Ordered list" },
    { label: "<li>", type: "tag", detail: "List item" },
    { label: "<table>", type: "tag", detail: "Table" },
    { label: "<tr>", type: "tag", detail: "Table row" },
    { label: "<td>", type: "tag", detail: "Table data cell" },
    { label: "<th>", type: "tag", detail: "Table header cell" },
    { label: "<form>", type: "tag", detail: "Form element" },
    { label: "<input>", type: "tag", detail: "Input field" },
    { label: "<button>", type: "tag", detail: "Button" },
    { label: "<select>", type: "tag", detail: "Dropdown select" },
    { label: "<option>", type: "tag", detail: "Select option" },
    { label: "<textarea>", type: "tag", detail: "Multi-line text input" },
    { label: "<label>", type: "tag", detail: "Form label" },
    { label: "<header>", type: "tag", detail: "Header section" },
    { label: "<footer>", type: "tag", detail: "Footer section" },
    { label: "<nav>", type: "tag", detail: "Navigation" },
    { label: "<main>", type: "tag", detail: "Main content" },
    { label: "<section>", type: "tag", detail: "Section" },
    { label: "<article>", type: "tag", detail: "Article" },
    { label: "<aside>", type: "tag", detail: "Sidebar content" },
    { label: "<link>", type: "tag", detail: "External resource link" },
    { label: "<meta>", type: "tag", detail: "Metadata" },
    { label: "<title>", type: "tag", detail: "Document title" },
    { label: "<style>", type: "tag", detail: "Inline styles" },
    { label: "<script>", type: "tag", detail: "JavaScript code" },
    { label: "<video>", type: "tag", detail: "Video player" },
    { label: "<audio>", type: "tag", detail: "Audio player" },
    { label: "<canvas>", type: "tag", detail: "Drawing canvas" },
    { label: "class", type: "keyword", detail: "CSS class attribute" },
    { label: "id", type: "keyword", detail: "Element ID" },
    { label: "href", type: "keyword", detail: "Link URL" },
    { label: "src", type: "keyword", detail: "Source URL" },
    { label: "alt", type: "keyword", detail: "Alternative text" },
    { label: "style", type: "keyword", detail: "Inline CSS" },
    { label: "type", type: "keyword" },
    { label: "name", type: "keyword" },
    { label: "value", type: "keyword" },
    { label: "placeholder", type: "keyword" },
  ],
  css: [
    { label: "color", type: "property", detail: "Text color" },
    { label: "background-color", type: "property", detail: "Background color" },
    { label: "background-image", type: "property", detail: "Background image" },
    { label: "background-size", type: "property", detail: "Background size" },
    { label: "background-position", type: "property", detail: "Background position" },
    { label: "background-repeat", type: "property", detail: "Background repeat" },
    { label: "font-size", type: "property", detail: "Font size" },
    { label: "font-weight", type: "property", detail: "Font weight" },
    { label: "font-family", type: "property", detail: "Font family" },
    { label: "font-style", type: "property", detail: "Font style" },
    { label: "text-align", type: "property", detail: "Text alignment" },
    { label: "text-decoration", type: "property", detail: "Text decoration" },
    { label: "text-transform", type: "property", detail: "Text transform" },
    { label: "line-height", type: "property", detail: "Line height" },
    { label: "letter-spacing", type: "property", detail: "Letter spacing" },
    { label: "margin", type: "property", detail: "Outer spacing" },
    { label: "margin-top", type: "property", detail: "Top margin" },
    { label: "margin-right", type: "property", detail: "Right margin" },
    { label: "margin-bottom", type: "property", detail: "Bottom margin" },
    { label: "margin-left", type: "property", detail: "Left margin" },
    { label: "padding", type: "property", detail: "Inner spacing" },
    { label: "padding-top", type: "property", detail: "Top padding" },
    { label: "padding-right", type: "property", detail: "Right padding" },
    { label: "padding-bottom", type: "property", detail: "Bottom padding" },
    { label: "padding-left", type: "property", detail: "Left padding" },
    { label: "border", type: "property", detail: "Border" },
    { label: "border-radius", type: "property", detail: "Border radius" },
    { label: "border-width", type: "property", detail: "Border width" },
    { label: "border-style", type: "property", detail: "Border style" },
    { label: "border-color", type: "property", detail: "Border color" },
    { label: "width", type: "property", detail: "Element width" },
    { label: "height", type: "property", detail: "Element height" },
    { label: "max-width", type: "property", detail: "Maximum width" },
    { label: "max-height", type: "property", detail: "Maximum height" },
    { label: "min-width", type: "property", detail: "Minimum width" },
    { label: "min-height", type: "property", detail: "Minimum height" },
    { label: "display", type: "property", detail: "Display type" },
    { label: "position", type: "property", detail: "Positioning" },
    { label: "top", type: "property", detail: "Top offset" },
    { label: "right", type: "property", detail: "Right offset" },
    { label: "bottom", type: "property", detail: "Bottom offset" },
    { label: "left", type: "property", detail: "Left offset" },
    { label: "z-index", type: "property", detail: "Stack order" },
    { label: "opacity", type: "property", detail: "Transparency" },
    { label: "overflow", type: "property", detail: "Overflow handling" },
    { label: "flex", type: "property", detail: "Flex grow/shrink" },
    { label: "flex-direction", type: "property", detail: "Flex direction" },
    { label: "flex-wrap", type: "property", detail: "Flex wrap" },
    { label: "justify-content", type: "property", detail: "Main axis alignment" },
    { label: "align-items", type: "property", detail: "Cross axis alignment" },
    { label: "gap", type: "property", detail: "Grid/Flex gap" },
    { label: "grid-template-columns", type: "property", detail: "Grid columns" },
    { label: "grid-template-rows", type: "property", detail: "Grid rows" },
    { label: "box-shadow", type: "property", detail: "Box shadow" },
    { label: "transition", type: "property", detail: "Transition" },
    { label: "transform", type: "property", detail: "Transform" },
    { label: "cursor", type: "property", detail: "Cursor style" },
    { label: "hover", type: "keyword", detail: "Hover pseudo-class" },
    { label: "focus", type: "keyword", detail: "Focus pseudo-class" },
    { label: "active", type: "keyword", detail: "Active pseudo-class" },
    { label: "before", type: "keyword", detail: "Before pseudo-element" },
    { label: "after", type: "keyword", detail: "After pseudo-element" },
    { label: "none", type: "keyword" },
    { label: "block", type: "keyword" },
    { label: "inline", type: "keyword" },
    { label: "flex", type: "keyword" },
    { label: "grid", type: "keyword" },
    { label: "relative", type: "keyword" },
    { label: "absolute", type: "keyword" },
    { label: "fixed", type: "keyword" },
    { label: "sticky", type: "keyword" },
    { label: "solid", type: "keyword" },
    { label: "dashed", type: "keyword" },
    { label: "center", type: "keyword" },
    { label: "space-between", type: "keyword" },
    { label: "space-around", type: "keyword" },
    { label: "inherit", type: "keyword" },
    { label: "initial", type: "keyword" },
    { label: "transparent", type: "keyword" },
    { label: "rgb", type: "function", detail: "RGB color" },
    { label: "rgba", type: "function", detail: "RGBA color" },
    { label: "hsl", type: "function", detail: "HSL color" },
    { label: "url", type: "function", detail: "URL reference" },
    { label: "var", type: "function", detail: "CSS variable" },
    { label: "calc", type: "function", detail: "Calculation" },
  ],
};

// AI completions cache
let aiDebounceTimer: ReturnType<typeof setTimeout> | null = null;
let lastAiRequest = "";
let lastAiResult: { label: string; type: string; detail: string; isAI: boolean }[] = [];
let activeView: EditorView | null = null;

async function fetchAICompletions(language: string, code: string, cursorPosition: number) {
  try {
    const res = await fetch("/api/ai-complete", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ language, code, cursorPosition }),
    });
    if (!res.ok) return [];
    const data = await res.json();
    const results = data.completions || [];
    // Re-trigger autocomplete to show the new AI results
    if (results.length > 0 && activeView) {
      setTimeout(() => startCompletion(activeView!), 50);
    }
    return results;
  } catch {
    return [];
  }
}

function createHighlightStyle(theme: any) {
  return HighlightStyle.define([
    { tag: tags.keyword, color: "#C678DD" },
    { tag: tags.operator, color: "#56B6C2" },
    { tag: tags.special(tags.variableName), color: "#E06C75" },
    { tag: tags.typeName, color: "#E5C07B" },
    { tag: tags.atom, color: "#D19A66" },
    { tag: tags.number, color: "#D19A66" },
    { tag: tags.bool, color: "#D19A66" },
    { tag: tags.definition(tags.variableName), color: "#61AFEF" },
    { tag: tags.string, color: "#98C379" },
    { tag: tags.special(tags.string), color: "#56B6C2" },
    { tag: tags.comment, color: theme.faint, fontStyle: "italic" },
    { tag: tags.variableName, color: theme.text },
    { tag: tags.local(tags.variableName), color: theme.text },
    { tag: tags.tagName, color: "#E06C75" },
    { tag: tags.bracket, color: "#ABB2BF" },
    { tag: tags.meta, color: "#ABB2BF" },
    { tag: tags.link, color: "#61AFEF", textDecoration: "underline" },
    { tag: tags.heading, color: "#E06C75", fontWeight: "bold" },
    { tag: tags.emphasis, fontStyle: "italic" },
    { tag: tags.strong, fontWeight: "bold" },
    { tag: tags.strikethrough, textDecoration: "line-through" },
    { tag: tags.self, color: "#E06C75" },
    { tag: tags.function(tags.variableName), color: "#61AFEF" },
    { tag: tags.propertyName, color: "#E06C75" },
  ]);
}

interface CodeEditorProps {
  language: string;
  value: string;
  onChange: (value: string) => void;
}

export default function CodeEditor({ language, value, onChange }: CodeEditorProps) {
  const editorRef = useRef<HTMLDivElement>(null);
  const viewRef = useRef<EditorView | null>(null);
  const { theme } = useTheme();

  useEffect(() => {
    if (!editorRef.current) return;

    if (viewRef.current) {
      viewRef.current.destroy();
    }

    const updateListener = EditorView.updateListener.of((update) => {
      if (update.docChanged) {
        onChange(update.state.doc.toString());
      }
    });

    const highlightTheme = createHighlightStyle(theme);

    // Custom autocomplete source from language keywords + AI
    const customCompletions = languageCompletions[language] || languageCompletions.javascript;

    const myAutocomplete = autocompletion({
      override: [
        (context: CompletionContext): CompletionResult | null => {
          const word = context.matchBefore(/\w*/);
          if (!word || (word.from === word.to && !context.explicit)) return null;

          const prefix = word.text.toLowerCase();

          // Static completions (always available immediately)
          const staticOptions = customCompletions.map((c) => ({
            label: c.label,
            type: c.type as any,
            detail: c.detail,
          }));

          // Cached AI completions matching current prefix
          const matchingAI = lastAiResult
            .filter((c) => c.label.toLowerCase().startsWith(prefix))
            .map((c) => ({
              label: c.label,
              type: c.type as any,
              detail: c.detail + " (AI)",
            }));

          // Trigger debounced AI fetch (fire-and-forget)
          const cursorPos = context.pos;
          const fullCode = context.state.doc.toString();
          const requestKey = `${language}:${cursorPos}:${fullCode}`;

          if (requestKey !== lastAiRequest) {
            lastAiRequest = requestKey;
            lastAiResult = []; // Clear stale results immediately
            if (aiDebounceTimer) clearTimeout(aiDebounceTimer);
            aiDebounceTimer = setTimeout(async () => {
              const results = await fetchAICompletions(language, fullCode, cursorPos);
              lastAiResult = results;
            }, 400);
          }

          return {
            from: word.from,
            options: [...matchingAI, ...staticOptions],
            validFor: /^\w*$/,
          };
        },
      ],
      activateOnTyping: true,
      maxRenderedOptions: 15,
    });

    const state = EditorState.create({
      doc: value,
      extensions: [
        lineNumbers(),
        highlightActiveLine(),
        highlightActiveLineGutter(),
        history(),
        foldGutter(),
        bracketMatching(),
        closeBrackets(),
        keymap.of([...defaultKeymap, ...historyKeymap]),
        languageExtensions[language] || javascript(),
        syntaxHighlighting(highlightTheme),
        myAutocomplete,
        updateListener,
        EditorView.lineWrapping,
        EditorView.theme({
          "&": {
            height: "100%",
            fontSize: "14px",
            backgroundColor: theme.bg,
          },
          ".cm-scroller": {
            fontFamily: "var(--font-geist-mono), monospace",
            overflow: "auto",
            backgroundColor: theme.bg,
          },
          ".cm-content": {
            padding: "16px 0",
            backgroundColor: theme.bg,
            caretColor: theme.text,
          },
          ".cm-gutters": {
            backgroundColor: "transparent",
            borderRight: `1px solid ${theme.border}`,
          },
          ".cm-lineNumbers .cm-gutterElement": {
            padding: "0 12px 0 16px",
            color: theme.faint,
          },
          ".cm-activeLine": {
            backgroundColor: `${theme.accent}08`,
          },
          ".cm-activeLineGutter": {
            backgroundColor: "transparent",
          },
          "&.cm-focused .cm-cursor, .cm-cursor": {
            borderLeftColor: theme.text,
            borderLeftWidth: "2px",
            borderLeftStyle: "solid",
          },
          "&.cm-focused .cm-selectionBackground, .cm-selectionBackground": {
            backgroundColor: `${theme.accent}20`,
          },
          ".cm-tooltip": {
            backgroundColor: theme.panel,
            border: `1px solid ${theme.border}`,
            borderRadius: "8px",
            overflow: "hidden",
          },
          ".cm-tooltip-autocomplete > ul": {
            maxHeight: "300px",
          },
          ".cm-tooltip-autocomplete > ul > li": {
            padding: "4px 12px",
            color: theme.text,
            fontSize: "13px",
          },
          ".cm-tooltip-autocomplete > ul > li[aria-selected]": {
            backgroundColor: `${theme.accent}20`,
            color: theme.accent,
          },
          ".cm-completionIcon": {
            color: theme.faint,
          },
          ".cm-completionDetail": {
            color: theme.faint,
            fontStyle: "normal",
            fontSize: "11px",
          },
        }),
      ],
    });

    viewRef.current = new EditorView({
      state,
      parent: editorRef.current,
    });
    activeView = viewRef.current;

    requestAnimationFrame(() => {
      viewRef.current?.focus();
    });

    return () => {
      if (viewRef.current) {
        viewRef.current.destroy();
        activeView = null;
      }
    };
  }, [language, theme]);

  // Sync external value changes with editor
  useEffect(() => {
    if (!viewRef.current) return;
    const currentContent = viewRef.current.state.doc.toString();
    if (value !== currentContent) {
      viewRef.current.dispatch({
        changes: { from: 0, to: currentContent.length, insert: value },
      });
    }
  }, [value]);

  return (
    <div
      ref={editorRef}
      style={{
        height: "100%",
        overflow: "hidden",
        borderRadius: "0 0 8px 8px",
      }}
    />
  );
}
